gotcha:
  FIRST_TIME_RUNNING: true
  EXTERNAL_SERVICE_MODE: "real"
  DATABASE_MODE: "real"
  DATABASE_URL: "www.amit.com"
  DATABASE_PASSWORD: "12345"
  system_email: "system@gmail.com"
  system_email_password: "123456"
  admin_user_name: "admin@gmail.com"
  admin_password: "admin"
  mapsAdapter: "develop"
  number_of_routes: 1
  minimum_password_length: 4
  maximum_password_length: 14
  minimum_distance_alert: 20
  number_of_coordinates: 8
  Server:
    default:
      host: "8000"
      port: "8080"
      protocol: "TCP"

rate-config:
  speed_changes_per_minute:
    0: 100
    1: 95
    2: 85
    3: 80
    4: 70
    5: 60
    6: 50

  brakes_per_minute:
    0: 100
    1: 95
    2: 85
    3: 80
    4: 70
    5: 50

  sharp_turns_per_minute:
    0: 100
    1: 85
    2: 80
    3: 70
    4: 50

  alerts_per_minute:
    0: 100
    1: 95
    2: 90
    3: 80
    4: 75
    5: 70
    6: 50

  on_sidewalk:
    0: 100
    10: 85
    20: 75
    30: 60
    40: 50
