gotcha:
  FIRST_TIME_RUNNING: true
  EXTERNAL_SERVICE_MODE: "real"
  DATABASE_MODE: "real"
  DATABASE_URL: "www.amit.com"
  DATABASE_PASSWORD: "12345"
  system_email: "system@gmail.com"
  system_email_password: "123456"
  admin_user_name: "admin@gmail.com"
  admin_password: "admin"
  mapsAdapter: "develop"
  number_of_routes: 1
  minimum_password_length: 4
  maximum_password_length: 14
  minimum_distance_alert: 20
  number_of_coordinates: 8
  orYarukEmail: "or_yaruk@gmail.com"
  cities_emails:
      "Tel-Aviv": "tel_aviv@gmail.com"
      "Beersheba": "beersheba@gmail.com"
      "Haifa": "haifa@gmail.com"
      "Netanya": "netanya@gmail.com"
  Server:
    default:
      host: "8000"
      port: "8080"
      protocol: "TCP"
